### ISSUE TITLE
Regularization including diaeresis

### ISSUE THREAD

**Issue by andreabernini** [DCLP/dclpxsltbox#118] opened 2015-03-19 10:19 UTC
P.Oxy. 71.4804 (TM 112359)

https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112359.xml#l88

Leiden+
<:εἱ4.- στήκει|reg| ι̣(¨)4.- [στηκει]:>

EpiDoc

```
  <choice><reg>εἱ<lb n="4" break="no"/>στήκει</reg><orig><hi rend="diaeresis><unclear>ι</unclear</hi><lb n="4" break="no"/><supplied reason="lost">στηκει</supplied></orig></choice>
```

Apparatus:
v.3-4. l. εἱ|στήκει : Ϊ|[ΣΤΗΚΕΙ]ϊ papyrus

What we would like to see is:
v.3-4. l. εἱ|στήκει : ϊ[στηκει] papyrus
or, perhaps,
v.3-4. l. εἱ|στήκει : ϊστηκει papyrus

**Comment by paregorios** [comment] 2015-04-30 21:34
@cgajjar05 would you please sift through the XSLT to see where ```<supplied reason="lost">``` is handled? I'd like you to investigate why, in the production of the apparatus entry, all the text contained therein is capitalized. It may be the case that this is an expected DDB style, but let's find the spot in the code where it's handled first, then discuss how to proceed.

**Comment by paregorios** [comment] 2015-05-04 18:35
odd capitalization seems to have been fixed when another similar problem was fixed, but we're still seeing problems with the order in which the contents of the ```<orig>``` are being rendered. For the XML cited above, we'd expect to see (in the apparatus):

 v.3-4. l. εἱ|στήκει : ϊ[στηκει] papyrus

(as indicated by @andreabernini) above, but now we're seeing:

 v.3-4. l. εἱ|στήκει : |[στηκει]ϊ papyrus

i.e., the iota and its diaeresis are appearing <b>after</b> the line break and supplement, instead of before them.

So the thing to hunt for is not where ```<supplied reason="lost">``` is handled, but where the code that's serializing the contents of ```<orig>``` for the apparatus display may be found and to see what logic bug might be leading to the behavior we're seeing.

**Comment by andreabernini** [comment] 2015-07-20 13:53
Another example (involving an alternative) is P.Oxy. 11.1380 (TM 63688), 142:

https://github.com/DCLP/idp.data/blob/dclp/DCLP/64/63688.xml#l244 

Leiden+: <:Ἶσι|alt| Ἶ(¨)σι:>

Displayed: or Ἶ(ϊ)σι

Expected: or Ἶσι : ϊσι papyrus

**Comment by wsalesky** [comment] 2017-04-07 13:16
The first example in this issue seems to be resolved:
See: http://dclp.github.io/dclpxsltbox/output/dclp/113/112359.html

`^ v.3-4. l. εἱ|στήκει : |[στηκει]ϊ papyrus`

@andreabernini  @paregorios  Can you confirm?

**Comment by wsalesky** [comment] 2017-04-07 15:26
@andreabernini @paregorios 
Regarding the second example: 

> Another example (involving an alternative) is P.Oxy. 11.1380 (TM 63688), 142:
> 
> https://github.com/DCLP/idp.data/blob/dclp/DCLP/64/63688.xml#l244
> 
> Leiden+: <:Ἶσι|alt| Ἶ(¨)σι:>
> 
> Displayed: or Ἶ(ϊ)σι
> 
> Expected: or Ἶσι : ϊσι papyrus

This is handled by an entirely different part of the XSLT. As I see it there is a bug in the XSLT that fails to add the contents of the preceding t:lem when it exists. 

XML:
`<app type="alternative"><lem>Ἶσι</lem><rdg><hi rend="diaeresis">Ἶ</hi>σι</rdg></app>`

Should output ` Ἶσι or Ἶ(ϊ)σι`, which it does in the title attribute: 
`<span title="Scribe wrote Ἶσι or Ἶ(ϊ)σι"> or Ἶ(ϊ)σι</span>`

I think it would be useful to have a few more example records with the expected display.
Thanks.

**Comment by rla2118** [comment] 2017-04-15 08:35
The first example (http://dclp.github.io/dclpxsltbox/output/dclp/113/112359.html) still doesn't display properly.  It should look like this: 

ϊ|[στηκει] papyrus

With the "ϊ" at the beginning of the word, not at the end.

As for the second example, there appears to be an encoding error. It's unclear what alternative is being proposed.

**Comment by wsalesky** [comment] 2017-04-15 21:04
@rla2118, thanks for the clarification. I will revisit the issue in the first example. 

As for the second example I do think there may be a bug in the way the the apparatus handles the 
`<app type="alternative">` elements, but am not familiar enough with the expected output to say for sure. @paregorios perhaps you could go over this with me at some point to I can get some clarification on the expectations for this part of the XSLT? 

It seems to me that the `tei:lem`, as a child of t:app/@alternative is not being out put in the apparatus. Here is another examples I have found:

http://dclp.github.io/dclpxsltbox/output/dclp/113/112364.html
As seen on screen: `^ i.17-18. or ἀναγέγρα|[φεν] ὅσοις`
HTML: i.17-18. `<span title="Scribe wrote ἀναγεγρα-[φότ]ο̣ς οἷς or ἀναγέγρα|[φεν] ὅσοις"> or ἀναγέγρα|[φεν] ὅσοις</span>`
XML: 
`<app type="alternative"><lem>ἀναγεγρα<lb n="18" break="no"/><supplied reason="lost">φότ</supplied><unclear>ο</unclear>ς οἷς</lem><rdg>ἀναγέγρα<lb n="18" break="no"/><supplied reason="lost">φεν</supplied> ὅσοις</rdg></app>`

I would think the screen view should this be: 
`^ i.17-18. ἀναγεγρα-[φότ]ο̣ς οἷς or ἀναγέγρα|[φεν] ὅσοις`

**Comment by wsalesky** [comment] 2017-04-21 13:23
This change only effects one xml file. 
**New branch:**  `svn.code.sf.net/p/epidoc/code/branches/dclp-issue118/example-p5-xslt`
**Problem:**  t:hi parent elements such as orig, erroneously being passed to recurse_back and recurse_forward templates.

**XSLT Changes:**
Add `<xsl:if test="not(parent::t:orig)">` to text-before and text-after variables. 

**Note:** The output is not quite what is request, but is correct according to my understanding of the apparatus generation. 
expected:
v.3-4. l. εἱ|στήκει : ϊ[στηκει] papyrus
output:
v.3-4. l. εἱ|στήκει : ϊ papyrus

The `|[στηκει] ` is not included because it follows a line break (\n) in the xml file. 

```
diff --git a/output/dclp/113/112359.html b/output/dclp/113/112359.html
index c445eacbc..8329fcf12 100644
--- a/output/dclp/113/112359.html
+++ b/output/dclp/113/112359.html
@@ -131,7 +131,7 @@
                                  <!--0--></a>τ̣ο̣ῦ̣ θ(εο)ῦ. τῇ̣ [ἐπαύριον εἱστήκει ὁ<a href="#to-app-app01" id="from-app-app01">(*)</a> Ἰωάν] -<br>——<br id="ar-l29">νης καὶ̣ ἐ̣[κ τῶν μαθητῶν αὐτοῦ δύο,]<br id="ar-l30"><span class="linenumber">30</span>καὶ̣ ἐ̣μ̣βλέ̣[ψας τῷ Ἰη(σο)ῦ περιπατοῦντι]<br id="ar-l31">λέγει, Ἴ<a href="#to-app-hi06" id="from-app-hi06">(*)</a>δε ὁ [ἀμνὸς τοῦ θ(εο)ῦ. καὶ ἀκούσαν-]<br id="ar-l32">[τ]ε̣ς οἱ δύο μ̣[αθηταὶ αὐτοῦ λαλοῦντος]<br id="ar-l33">ἠκολούθη[σαν τῷ Ἰη(σο)ῦ στραφεὶς δὲ ὁ]<br id="ar-l34">Ἰη(σοῦ)ς καὶ θεα̣[σάμενος- ca.12 -]<br id="ar-l34">[14 lines missing]<br id="ar-l49"><span class="linenumber">49</span>[- ca.23 -ἑρμη-]<br id="ar-l50"><span class="linenumber">50</span>ν̣εύεται Π̣[έτρος. τῇ ἐπαύριον ἠθέλη-]<br id="ar-l51">[σ]εν ἐ̣ξελ[θεῖν εἰς τὴν Γαλιλαίαν, καὶ]<br id="ar-l52">[εὑρίσ]κ̣ε̣[ι Φίλιππον. καὶ λέγει αὐτῷ ὁ Ἰη(σοῦ)ς,]<br id="ar-l53">[ἀ]κολούθ[ει μοι. ἦν δὲ ὁ Φίλιππος ἀπὸ]<br id="ar-l54">Βηθ’σαϊ<a href="#to-app-hi07" id="from-app-hi07">(*)</a>δ̣[ά- ca.20 -] 
                            </div>  
                            <h2>Apparatus</h2>
-                           <div id="apparatus"><br><a id="to-app-hi01" href="#from-app-hi01">^</a> v.3. <span>ϋμ̣ῶ̣ν papyrus</span><br><a id="to-app-choice01" href="#from-app-choice01">^</a> v.3-4. <span title="Scribe wrote ι̣|[στηκει], for which read εἱ|στήκει"> l. εἱ|στήκει</span> : <span>|[στηκει]ϊ papyrus</span><br><a id="to-app-hi03" href="#from-app-hi03">^</a> v.5. <span>ϊνα̣ papyrus</span><br><a id="to-app-hi04" href="#from-app-hi04">^</a> v.6. <span>ϋποδη papyrus</span><br><a id="to-app-hi05" href="#from-app-hi05">^</a> v.27. <span>ϋιοσ papyrus</span><br><a id="to-app-app01" href="#from-app-app01">^</a> r.28. <span title="Scribe wrote εἱστήκει ὁ or εἱστήκει"> or εἱστήκει</span><br><a id="to-app-hi06" href="#from-app-hi06">^</a> r.31. <span>ϊδε papyrus</span><br><a id="to-app-hi07" href="#from-app-hi07">^</a> r.54. <span>βηθ’σαϊδ̣[ά- ca.20 -] papyrus</span></div>
+                           <div id="apparatus"><br><a id="to-app-hi01" href="#from-app-hi01">^</a> v.3. <span>ϋμ̣ῶ̣ν papyrus</span><br><a id="to-app-choice01" href="#from-app-choice01">^</a> v.3-4. <span title="Scribe wrote ι̣|[στηκει], for which read εἱ|στήκει"> l. εἱ|στήκει</span> : <span>ϊ papyrus</span><br><a id="to-app-hi03" href="#from-app-hi03">^</a> v.5. <span>ϊνα̣ papyrus</span><br><a id="to-app-hi04" href="#from-app-hi04">^</a> v.6. <span>ϋποδη papyrus</span><br><a id="to-app-hi05" href="#from-app-hi05">^</a> v.27. <span>ϋιοσ papyrus</span><br><a id="to-app-app01" href="#from-app-app01">^</a> r.28. <span title="Scribe wrote εἱστήκει ὁ or εἱστήκει"> or εἱστήκει</span><br><a id="to-app-hi06" href="#from-app-hi06">^</a> r.31. <span>ϊδε papyrus</span><br><a id="to-app-hi07" href="#from-app-hi07">^</a> r.54. <span>βηθ’σαϊδ̣[ά- ca.20 -] papyrus</span></div>
                         </div>
                      </div>
                   </div>
```
I think there is more then one way to solve this issue, and am waiting to hear back from @paregorios  about the XSLT before I submit the code for review.

**Comment by paregorios** [comment] 2017-05-03 13:01
@wsalesky is this on hold while you investigate apparatus refactoring, or is there something else I should be doing here?

**Comment by wsalesky** [comment] 2017-05-03 13:04
@paregorios it is on hold. I want to  review @leoba's recent changes first.

**Comment by wsalesky** [comment] 2017-05-18 17:33
Resolved by #119

**Comment by paregorios** [comment] 2017-05-22 19:12
Unfortunately, after merging changes for #119 and regenerating, I see this for TM 112359:

![screen shot 2017-05-22 at 2 09 09 pm](https://cloud.githubusercontent.com/assets/263285/26324423/533df194-3ef8-11e7-8894-c74f92197b28.png)

instead of ```v.3-4. l. εἱ|στήκει : ϊ papyrus``` or ```v.3-4. l. εἱ|στήκει : ϊ[στηκει] papyrus``` as discussed above. 

I.e., the iota with diaeresis is still (again?) appearing after the rest of the word, instead of before it.

**Comment by wsalesky** [comment] 2017-05-23 13:18
@paregorios  Could this possibly be a merge issue? When running the xslt from the issue119 branch: 

It produces: 
<img width="331" alt="screen shot 2017-05-23 at 9 17 11 am" src="https://cloud.githubusercontent.com/assets/1168206/26356009/a5aba638-3f98-11e7-8505-7c4c4bb6d3c4.png">

Which matches expected behavior. The above screen shot looks like a merge of #243, maybe not #119?

**Comment by paregorios** [comment] 2017-05-23 20:40
I'm investigating

**Comment by paregorios** [comment] 2017-05-23 20:53
When I switch to the issue119 branch (in svn), I get the result @wsalesky, but when I create a copy of "dclp" branch and merge issue119 into it, I get the screenshot shown above. Currently trying to work out a diff mechanism so I can see what's getting stomped, but [svn is lame](https://stackoverflow.com/questions/3210700/subversion-how-to-difference-between-modified-working-copy-and-alternate-branc) so this is hard.

**Comment by paregorios** [comment] 2017-05-24 13:52
I am actively working on fixing the mess I made here.

**Comment by wsalesky** [comment] 2017-05-24 13:54
Okay, let me know if you want me to do anything.

**Comment by paregorios** [comment] 2017-05-24 23:07
[The new epidoc-xslt git repos](https://github.com/DCLP/epidoc-xslt) is ready to go. 

Unfortunately, I have been unable to get the code in https://github.com/DCLP/epidoc-xslt/tree/issue118 to produce the target output expected for this ticket, so I fear I'm going to have to ask you @wsalesky to try to recreate your fixes for this issue. 

Specifically, I note the following regressions for apparatus in TM 112359 when I run transforms either with "master" or with the "issue118" branch of https://github.com/DCLP/epidoc-xslt.

1. In the portion of the apparatus entry for lines 3-4 that derives from the ```<orig>``` element, the initial iota with diaeresis is appearing after the line break and supplemented characters, instead of in front of them.

2. Some characters inside ```<orig>``` are getting capitalized even though the ```<orig>``` is a child of ```<choice>```. This is only happening in the apparatus, not in the main text. 

Actual/Current:

```^ v.3-4. l. εἱ|στήκει : |[ΣΤΗΚΕΙ]ϊ papyrus```

Desired:

```^ v.3-4. l. εἱ|στήκει : ϊ|[στηκει] papyrus```

**Comment by wsalesky** [comment] 2017-05-25 17:14
See branch for the fix: https://github.com/DCLP/epidoc-xslt/tree/issue272

**Comment by paregorios** [comment] 2017-06-01 21:02
@wsalesky I have inspected the changes in epidoc-xslt branch issue272 and, after verifying that I have them locally, have run transforms with them. They make no changes to the HTML output. I am still seeing [the incorrect output I noticed previously](https://github.com/DCLP/dclpxsltbox/issues/118#issuecomment-303877406).

Can you please check to see whether you have local changes that have not been pushed to that branch? If not, please re-run transforms locally and see if you are getting correct output or seeing the same regression that I am. If you are still getting correct output, then we'll need to schedule a meeting to talk through all this and try to figure out what's different between our workspaces.

**Comment by wsalesky** [comment] 2017-06-08 15:05
**XSLT Updated:**  `epidoc-xslt/example-p5-xslt/tpl-apparatus.xsl`
Edited `<xsl:template name="hirend">` to look for `parent::following-sibling/preceding-sibling` axis if there are no `following-sibling/preceding-sibling` of the current element (t:hi).

**Branch:** `https://github.com/DCLP/epidoc-xslt/tree/issue118-refactor`

**HTML files changed:** 
```
	modified:   output/dclp/113/112359.html
	modified:   output/dclp/371/370041.html
```

**HTML output:** 

^ v.3-4. l. εἱ|στήκει : ϊ papyrus

This is correct according to the logic in the apparatus code. Which prints out content only until the first space, line break or tab character: `<xsl:when test="matches($step, '[\s\n\r\t]')">`

In order to get: 
v.3-4. l. εἱ|στήκει : ϊ[στηκει] papyrus

We would need to change the logic to only look for spaces. 

@paregorios  This is ready for review, with the above caveat.

**Comment by paregorios** [comment] 2017-06-09 21:38
resolved

**Closed by paregorios** 2017-06-09 21:38 UTC
Labels: enhancement, priority: high, review, tweak XSLT
