### ISSUE TITLE
Display of "Front Matter" and "Commentary"

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#156] opened 2015-09-16 15:14 UTC
The following "medical papyri" now have front matter and commentary in the XML files:

https://github.com/DCLP/idp.data/blob/dclp/DCLP/70/69006.xml
https://github.com/DCLP/idp.data/blob/dclp/DCLP/70/69032.xml
https://github.com/DCLP/idp.data/blob/dclp/DCLP/65/64507.xml
https://github.com/DCLP/idp.data/blob/dclp/DCLP/120/119317.xml
https://github.com/DCLP/idp.data/blob/dclp/DCLP/120/119323.xml
https://github.com/DCLP/idp.data/blob/dclp/DCLP/120/119324.xml

Front matter div is: ```<div type="commentary" subtype="frontmatter" xml:space="preserve">```
e.g.
https://github.com/DCLP/idp.data/blob/dclp/DCLP/120/119323.xml#L74

Commentary div is: ```<div type="commentary" subtype="linebyline">```
e.g.
https://github.com/DCLP/idp.data/blob/dclp/DCLP/120/119323.xml#L93-L102

There is XSLT that handles front matter and commentary for both preview and PN display. Not sure where it is, but presume that finding it and tweaking here and there should not be too time consuming.

**Comment by paregorios** [comment] 2015-09-17 15:22
@jcowey I gather from a quick look at http://dclp.github.io/dclpxsltbox/output/dclp/70/69006.html that the front matter and commentary are not currently displaying, so what you're suggesting above is we hunt down presumed existing code for display of same and wire it in for items in the DCLP collection.

If that's the case, can you tell me (if you know) for which collections (e.g., DDB) said code does currently work in PN? Thanks.

**Comment by jcowey** [comment] 2015-09-17 16:40
The following files show front matter and commentary:
http://papyri.info/ddbdp/p.got;;54dgtl
http://papyri.info/ddbdp/p.got;;29dgtl

The XML files they draw on is:
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.got/p.got.54dgtl.xml
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.got/p.got.29dgtl.xml

**Comment by jcowey** [comment] 2015-09-17 16:51
And yes I was indeed suggesting that it is a case of "hunt down presumed existing code for display of same and wire it in for items in the DCLP collection."

**Comment by leoba** [comment] 2015-09-20 21:37
Both 
<div type="commentary" subtype="frontmatter" xml:space="preserve"> and <div type="commentary" subtype="linebyline"> are processed in htm-teidiv.xml (https://github.com/DCLP/dclpxsltbox/blob/master/xslt/pn-xslt/htm-teidiv.xsl#L18-L19), but it's obviously not working correctly. This file should provide the heading and apply templates for the div contents.

**Comment by paregorios** [comment] 2015-09-21 15:04
It may not be getting invoked when processing metadata for collection==dclp. The relevant control flow, iirc, is in metadata-dclp.xslt

**Comment by leoba** [comment] 2015-10-04 21:26
@jcowey and @paregorios I am making progress on this. However both https://github.com/DCLP/idp.data/blob/dclp/DCLP/70/69006.xml and https://github.com/DCLP/idp.data/blob/dclp/DCLP/120/119317.xml have `tei:listBibl` in the `div[@type='commentary'][@subtype='frontmatter']` which are causing display issues. Can y'all please let me know if this is an encoding issue (i.e., `tei:listBibl` is not allowed in that div) or if the XSLT will need to be able to handle it.

**Comment by jcowey** [comment] 2015-10-05 21:22
Maybe have a look at
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.got/p.got.54dgtl.xml#L77
which with papyri.info XSLT can be seen to display in 
http://papyri.info/ddbdp/p.got;;54dgtl

**Comment by leoba** [comment] 2015-10-11 23:49
@jcowey please check out the branch issue156 (both dclpxsltbox and navigator) and see if that works as expected.

**Comment by paregorios** [comment] 2015-10-12 13:14
fyi I aim to look at this myself this week, but it might be later in the week before I get to it.

**Comment by jcowey** [comment] 2015-10-12 13:29
Using 
https://github.com/DCLP/idp.data/blob/dclp/DCLP/70/69006.xml
as a test case
I looked at 
http://dclp.github.io/dclpxsltbox/output/dclp/70/69006.html
There I do not see either Front Matter or Commentary.
Maybe there needs to be a rerun of the output before changes are visible.

**Comment by paregorios** [comment] 2015-10-12 13:32
Yes, if you want to see it now you'd need to run the transforms locally. I'll update after I test.

**Comment by paregorios** [comment] 2015-12-18 22:08
I've had a first pass at reviewing the results of the changes made by @leoba at DCLP/navigator@ 01b06f5, but I'm going to need to dig a little deeper. In my test run, at least some of the commentary sections had extraneous navigator-related nav in the middle, possibly caused by examples getting processed by unexpected templates. This is really just a note to myself to know where to pick up when I get back to looking at this.

**Comment by leoba** [comment] 2016-01-08 10:52
Thanks, this is helpful. I'll take another look myself.

**Comment by leoba** [comment] 2016-01-17 19:33
Tom, I'm not sure what you mean by "navigator-related nav in the middle" but I have noted (and mentioned above in comments from October 4 and following) that there is an issue with the display of `listbibl` - is that what you're referring to? I didn't see anything else amiss when I ran the transform locally. Assuming that is the issue, I was able to fix it by modifying navigator/epidoc-xslt/htm-teilistbiblandbibl.xsl to transform `listbibl` one way when an ancestor is `div[type='commentary']` and another (as an unordered list) otherwise. However when I went to commit the change, I received a message that the epidoc-xslt files are in gitignore, so I don't know if it's really okay to change them. If not, I'll look for another way to deal with the issue.

**Comment by paregorios** [comment] 2016-02-12 14:57
@leoba the files in ```navigator/epidoc-xslt/``` are a subversion checkout not controlled by git, which is why they are listed in ```.gitignore``` ([viz step 6 in the dclpxsltbox setup instructions](https://github.com/DCLP/dclpxsltbox#setup)).

You should be able to ```cd``` into ```navigator/epidoc-xslt``` and then use ```svn add``` and ```svn commit``` to publish the changes back to sourceforge.

**Comment by leoba** [comment] 2016-02-21 20:19
@paregorios I am unable to commit to svn (`Transmitting file data .svn: E000013: Commit failed (details follow):
svn: E000013: Can't open file '/svn/p/epidoc/code/db/txn-current-lock': Permission denied`) - guessing that I don't have permission to commit? Can you check on this?

**Comment by leoba** [comment] 2016-02-28 22:25
Committed.

**Comment by paregorios** [comment] 2016-03-09 21:55
I've done a transform run with this, and I see that my "navigator nav" comment is about the same thing @leoba noted above concerning ```listBibl``` in front matter. The presence of the ```listBibl``` wrapping a single bibl is, per @jcowey, a oddity introduced by the in-browser editor, for which I will certainly be opening a ticket. Meanwhile, I'm going to take this ticket temporarily and see how hard it would be to test for this condition and bypass it so as not to trigger the navigator default bibliographic rendering, which is what we're seeing in the output.

**Comment by paregorios** [comment] 2016-03-11 15:50
I'm still chasing the listBibl problem. There's now [an open ticket against the papyri.info navigator for it](https://github.com/papyri/sosol/issues/11).

**Closed** 2016-10-25 20:23 UTC
Labels: enhancement, priority: urgent, tweak XSLT
