### ISSUE TITLE
handle supplement parallel in XSLT

### ISSUE THREAD

**Issue by andreabernini** [DCLP/dclpxsltbox#120] opened 2015-03-20 13:36 UTC
See for instance TM 112362 (P.Oxy. 71.4807)

https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112362.xml#l107
https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112362.xml#l108

**Comment by HolgerEssler** [comment] 2015-03-20 14:27
I suppose the current convention would be:
Leiden+: _[αβγ]_	
xml: <supplied reason="undefined" evidence="parallel">αβγ</supplied>

Cf. however my request in your LitPapText spreadsheet, line 62.

**Comment by paregorios** [comment] 2015-03-25 08:59
by "low corner brackets" do you mean http://www.fileformat.info/info/unicode/char/23a3/index.htm and http://www.fileformat.info/info/unicode/char/23a6/index.htm as oppposed to "[" and "]"?

**Comment by rla2118** [comment] 2015-03-25 11:13
Yes, Tom, that looks right.

**Comment by paregorios** [comment] 2015-03-25 11:15
And what is the semantic significance a-la Leiden of such brackets?

**Comment by HolgerEssler** [comment] 2015-03-25 11:42
I resend my original comment as it was not displayed as I intended it:

I suppose the current convention would be:
Leiden+: _[αβγ]_
xml: <supplied reason="undefined" evidence="parallel">αβγ</supplied>

Cf. however my request in your LitPapText spreadsheet, line 62.
>
> And what is the semantic significance a-la Leiden of such brackets?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DCLP/dclpxsltbox/issues/120#issuecomment-85986124>.
>


-- 
Dr. Holger Essler, AR
Institut für Klassische Philologie I
Residenzplatz 2 (Südflügel)
D-97070 Würzburg

Tel.:            +49-931-31-85632
email:           Holger.Essler@uni-wuerzburg.de
Institutsseite:  www.klassphil.uni-wuerzburg.de
Epikurzentrum:   www.epikur-wuerzburg.de

**Comment by paregorios** [comment] 2015-03-25 13:59
So, @HolgerEssler the task for the technical team then is to modify the XSLT stylesheets to insert the relevant Unicode characters, yes?

**Comment by HolgerEssler** [comment] 2015-03-25 14:05
Yes, that is correct.

**Comment by HolgerEssler** [comment] 2015-03-25 14:29
Probably the Text Leiden+ Documentation at  
http://papyri.info/editor/documentation?docotype=text should also be  
updated:
   The entry under "supplied parallel lost" (without specific content)  
could be merged with/replaced by the entry under "supplied parallel"  
(with example http://papyri.info/ddbdp/p.berl.leihg;2;39).

**Comment by paregorios** [comment] 2015-04-30 19:59
See #134 for a separate ticket about updating Leiden+ documentation.

**Comment by paregorios** [comment] 2015-04-30 20:22
Reformulating the remaining technical task here:

For XML like ```<supplied evidence="parallel">...</supplied>``` the behavior of the XSL should be modified/extended to:

 * prepend [U+23A3](http://www.fileformat.info/info/unicode/char/23a6/index.htm)
 * process the child nodes
 * append [U+23A6](http://www.fileformat.info/info/unicode/char/23a6/index.htm)

Caveats:

 * whatever the value of the ```reason``` attribute, or even in its absence, this convention should be observed
 * do not change any handling for collections other than DCLP

Example files for testing:

 * TM 112362 (P.Oxy. 71.4807), lines [107](https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112362.xml#l107) and [108](https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112362.xml#l108)

**Comment by paregorios** [comment] 2015-04-30 20:24
See also: 

 * [EpiDoc Guidelines bug report](https://sourceforge.net/p/epidoc/bugs/141/)
 * [Papyri.info basecamp discussion](https://basecamp.com/2517156/projects/6217125/messages/41497119)

**Comment by paregorios** [comment] 2015-04-30 20:26
@HolgerEssler and @andreabernini please review my summation of the tasks [as indicated above](https://github.com/DCLP/dclpxsltbox/issues/120#issuecomment-97955271). If you concur, we will move forward to implement.

**Comment by paregorios** [comment] 2015-04-30 20:28
blocker for #134

**Comment by paregorios** [comment] 2015-04-30 21:16
[Have verified that DDB does not want to see this change affect their collection](https://basecamp.com/2517156/projects/6217125/messages/41497119#comment_277964187), so note again [my caveat above](https://github.com/DCLP/dclpxsltbox/issues/120#issuecomment-97955271): this behavior change should be for DCLP texts only.

**Comment by HolgerEssler** [comment] 2015-05-02 21:19
I concur.

**Comment by paregorios** [comment] 2015-05-04 15:37
I did some related work on this in the EpiDoc stylesheets on Friday. Will continue to work on rolling through the relevant changes to us and adding our DCLP-related logic this week.

**Comment by paregorios** [comment] 2017-02-10 19:41
@leoba would you please put this ticket at the top of your list for xslt things to look at next? The issue is clearly laid out in [this comment above](https://github.com/DCLP/dclpxsltbox/issues/120#issuecomment-97955271). Contra my 2015 self's additional comments, I cannot find any code changes I made relevant to this issue.

This one will, I think, require intervention in the EpiDoc stylesheets, rather than the navigator ones. Here's what I think will be required:

 - Add a new template to [teisupplied.xsl](https://sourceforge.net/p/epidoc/code/HEAD/tree/branches/dclp/example-p5-xslt/teisupplied.xsl) in order to catch ```<supplied evidence="parallel">``` only when the collection is "dclp". It should then call the named template "supplied-parallel". All of the templates in the file right now first match on the ```reason``` attribute and are agnostic as to collection. 
 - Add code to the named template "supplied-parallel", which is in [htm-teisupplied.xsl](https://sourceforge.net/p/epidoc/code/HEAD/tree/branches/dclp/example-p5-xslt/htm-teisupplied.xsl), in order to emit the desired brackets when the collection is "dclp". For other collection values, behavior should remain unchanged.

**Comment by leoba** [comment] 2017-02-14 02:05
Done as requested and committed to Sourceforge.

**Comment by paregorios** [comment] 2017-02-22 17:27
Code commit on EpiDoc sourceforge SVN was https://sourceforge.net/p/epidoc/code/2495/

**Closed by paregorios** 2017-02-22 17:28 UTC
Labels: blocker, enhancement, priority: high, review, tweak XSLT
