### ISSUE TITLE
Display of multiple lacunas

### ISSUE THREAD

**Issue by HolgerEssler** [DCLP/dclpxsltbox#55] opened 2014-11-19 21:55 UTC
In TM 62419
the beginning of col. 15, 2 in the edition reads:
---   ̣ ̣ ̣ ̣ ̣ φ]αῦλον
Leiden+ encoding would be
[.?][.5] [φ]αῦλον
XML :
`<gap reason="lost" extent="unknown" unit="character"/><gap reason="lost" quantity="5" unit="character"/> <supplied reason="lost">φ</supplied>αῦλον`
However, preview is grouping the gaps in the wrong way:
[ -ca.?- ][φ]αῦλον

**Comment by leoba** [comment] 2015-09-20 20:29
I'd like to work on this, but the TM 62419 file that I am using (from the dclp branch of idp.data: https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62419.xml) doesn't have the Greek text in it. @HolgerEssler are you using a data file from a different branch?

**Comment by paregorios** [comment] 2015-09-21 15:14
I can't find it either. I did the following inside idp.data/DCLP (dclp branch) and got no hits:

```
grep -R '<supplied reason="lost">φ</supplied>αῦλον' *
```

@jcowey any ideas?

**Comment by jcowey** [comment] 2015-09-21 15:39
I also searched for this last night and failed to find the Greek. I suspect Greek was entered using the editor in papyri.info for testing and entering and then not added to the existing XML file

**Comment by leoba** [comment] 2015-10-11 23:51
@HolgerEssler if you can update the TM 62419 in master to include the Greek (or if it's in another branch you can point me to, or if you can point to another text that is in master) I will work on this. Unfortunately I can't do much without the Greek.

**Comment by HolgerEssler** [comment] 2015-10-12 00:18
The text was encoded quite a while ago, but unfortunately is still in 
the pipeline (we are waiting for the processing by Daniel Riano). If the 
Leiden+, xml and preview output quoted above are not sufficient, I think 
the quickest way would be to look for other examples in the texts where 
the  sequence of <gap reason="lost" extent="unknown" 
unit="character"/><gap reason="lost" quantity="X" unit="character"/> occurs.

**Comment by HolgerEssler** [comment] 2015-10-27 23:47
The Greek text has now been included in the file of TM 62419.

**Comment by jcowey** [comment] 2015-10-28 07:43
In TM 62419 the beginning of col. 15, 2 in the edition reads:
--- ̣ ̣ ̣ ̣ ̣ φ]αῦλον
Leiden+ encoding would be
[.?][.5] [φ]αῦλον
XML :
<gap reason="lost" extent="unknown" unit="character"/><gap reason="lost" quantity="5" unit="character"/> <supplied reason="lost">φ</supplied>αῦλον
However, preview is grouping the gaps in the wrong way:
[ -ca.?- ][φ]αῦλον
https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62419.xml#L2042

**Comment by leoba** [comment] 2016-01-23 22:25
If I'm reading the documentation in the XSLT correctly this is the way the process is supposed to work - it's a feature not a bug. See `tpl-reasonlost.xsl` (this line and throughout):

https://github.com/DCLP/dclpxsltbox/blob/master/xslt/pn-xslt/tpl-reasonlost.xsl#L17

For a gap from `y` to `x`, "If `y` is a `text()` then output `'['` If `y` is `'lost'` then nothing"

So it seems the gaps are designed to run together if the preceding gap is `lost`. Let me know if I've misread this, or if it should be changed.

**Comment by HolgerEssler** [comment] 2016-01-23 22:56
I think it should be changed to a display that omits square brackets in
between, but does not lump together the content/extent of different
gap-elements following each other (i.e. I would like to avoid that
[---...] simply becomes [ -ca.?- ].
However there is an additional issue: the preview [ -ca.?- ][φ]αῦλον
also contains superfluous square brackets in the middle. It should in
any case read [ -ca.?- φ]αῦλον.

**Comment by leoba** [comment] 2016-01-24 23:05
@HolgerEssler can you show me how exactly you would expect / would like to see `<gap reason="lost" extent="unknown" unit="character"/><gap reason="lost" quantity="5" unit="character"/> <supplied reason="lost">φ</supplied>αῦλον` in preview?

**Comment by HolgerEssler** [comment] 2016-01-24 23:17
My preferred display would be everything in one set of square brackets:
[ -ca.?- ̣ ̣ ̣ ̣ ̣  φ]αῦλον

**Comment by leoba** [comment] 2016-01-31 21:45
Making a note for record: There is a bug where `<gap>`s with `@reason='lost'` next to each other don't display correctly. When there are two, the first displays correctly and then closes, and the second is ignored (that's what we are seeing here). When there are three [I don't know if this ever happens irl] the first displays, the second is ignored, and the third displays as a set of closed brackets []. If the `@reason` value of the gaps are different, this doesn't happen. I will continue to work on this so it displays as requested by @HolgerEssler.

**Comment by leoba** [comment] 2017-04-29 20:28
@HolgerEssler cc: @jcowey @paregorios  I have a potential fix for this but before I upload the code I want to make sure it really does what you want it too - it may be too broad.

Looking at 62419.html, column 15 now displays as:

[ -ca.?- ]πε̣ρ λ[  ̣  ̣  ̣]π[ -ca.?- ]
[ -ca.?- ] [φ]α̣ῦλον [ἦ]θο̣[ς -ca.?- ]
[ -ca.?- ]ο̣[0-1]ρ̣[0-1]η [ἐ]κθ[ -ca.?- ]
[ -ca.?- ]τ̣ε[  ̣  ̣  ̣  ̣]ο̣ς̣[ -ca.?- ]
5[ -ca.?- ] [ἀνα]γκάζ[ει] τῆς φυ[σ -ca.?- ]
[ -ca.?- ] [ἦ]χος̣ κ̣[ -ca.?- ]
[- ca.18 -]
[ -ca.?- ]ι̣αισπ[ -ca.?- ]
[ -ca.?- ]ν̣[ -ca.?- ]
10[ -ca.?- ]ο̣υον̣[ -ca.?- ]
[ -ca.?- ]ο[ -ca.?- ]
[ca.4 lines missing]

There are a ton of gaps there that aren't currently displaying. With my change (which is undoing a change that was done specifically to keep adjacent gaps from displaying - there is a comment to indicate this) this appears:

[ -ca.?-   ̣]πε̣ρ λ[  ̣  ̣  ̣]π[ -ca.?- ]
[ -ca.?-   ̣  ̣  ̣  ̣  ̣ φ]α̣ῦλον [ἦ]θο̣[ς -ca.?- ]
[ -ca.?-   ̣  ̣  ̣]ο̣[0-1]ρ̣[0-1]η [ἐ]κθ[ -ca.?- ]
[ -ca.?- ]τ̣ε[  ̣  ̣  ̣  ̣]ο̣ς̣[ -ca.?- ]
5[ -ca.?- -1-2- ἀνα]γκάζ[ει] τῆς φυ[σ -ca.?- ]
[ -ca.?- - ca.9 - ἦ]χος̣ κ̣[ -ca.?- ]
[- ca.18 -]
[ -ca.?- - ca.10 -]ι̣αισπ[ -ca.?- ]
[ -ca.?- - ca.9 -]ν̣[ -ca.?- ]
10[ -ca.?- - ca.9 -]ο̣υον̣[ -ca.?- ]
[ -ca.?-   ̣  ̣  ̣  ̣  ̣  ̣  ̣  ̣]ο[ -ca.?- ]
[ca.4 lines missing]

If this is what you want let me know and I will commit the code for review.

**Comment by paregorios** [comment] 2017-05-02 14:48
@jcowey @HolgerEssler @rla2118 @rogerbagnall please review per Dot's comment above. cc. @wsalesky

**Comment by rogerbagnall** [comment] 2017-05-03 09:18
Holger's desideratum does not seem to correspond to any situation that I have had reason to deal with in a papyrus. If the intention is to say that a lacuna is a minimum of (say) 5 characters long but is in fact greater by some unknown amount, then this looks OK to me. But since it was Holger's query, I don't think I have any independent wisdom on it.

**Comment by HolgerEssler** [comment] 2017-05-03 09:52
I am happy with the fix by @leoba and suggest to commit and close the issue.

**Comment by paregorios** [comment] 2017-05-03 13:29
@leoba please merge your changes

**Comment by leoba** [comment] 2017-05-03 13:50
@paregorios changes merged. I did leave that bit of code that originally kept the adjacent gaps from displaying, commented out, along with a comment of my own that I removed it for issue 55, in case this causes issues later.

**Comment by paregorios** [comment] 2017-05-09 15:07
This change has been committed and newly-generated HTML posted at http://dclp.github.io/dclpxsltbox/output/dclp/

**Closed by paregorios** 2017-05-09 15:07 UTC
Labels: bug, deploy, in work, priority: medium, tweak XSLT
